title: Data Nomad
author: Xtines
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Writing on the intersection of business, data products, commerce. Occasional thoughts on good food, books and traveling. 
# social links
twitter_username: your-twitter-handle
github_username:  Xtines

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
